### PR TITLE
Allow clearance_level to be an array.

### PR DESCRIPTION
**Pull request by god-anubis**
The important aspect of this change (which is why I made it in the first place) is to allow users etc. to have multiple clearance_levels. This way a user can be a post_editor, a group_administrator and an article_author and if ANY clearance level is sufficient to authorise an action, it will be authorised.
Now users do not have a single role / clearance_level but the application can use a way more modular approach to roles / clearance_levels.
A somewhat equal functionality could of course be also mapped with the clearance_level function of the user model but this way you would need a specific clearance_level for each and every combination of 'actual' clearance_levels. In my opinion this is cumbersome and error prone.
This is why keeper.lets? accepts arrays.

Allowing clearance_level to be an array for keeper.let is mostly for symmetry, because as Matías pointed out this really is syntactic sugar <https://en.wikipedia.org/wiki/Syntactic_sugar> for 
the following:

    class ArticlesController < ApplicationController
       let :role_one, [:index, :show]
       let :role_two, [:index, :show]

       # Or
       [:role_one, :role_two].each { |role| let role, [:index, :show] }

       # ...
    end

To turn it into:

    class ArticlesController < ApplicationController
       let [:role_one, :role_two], [:index, :show]

       # Or maybe even better
       let :role_one, :role_two, [:index, :show]  # would this really work? my ruby fu is not good enough to know

       # ...
    end

### CODE REVIEW

**Comment by matiasgagliano** [comment]
Hi @god-anubis, I initially thought that you were talking just about defining several clearance levels in the same authorization statement (in the same `let` call) but now that you've explained it further I see that your main concern is actually handling users/sessions with multiple clearance levels. This is much more than plain *syntactic sugar* and is a perfectly valid use case. Although a vertical role hierarchy might be a better practice in general, other application designs might be impossible without concurrent roles over the same entity.

My first concern is the `Keeper` class. For how this reads `keeper.lets? [:user, :guest], :show, :profiles` most would expect it to be true only if **all** the clearance levels in the list are allowed, not if at least one of them is allowed. It's better to leave it untouched, and `Keeper#let` too for consistency.  There are a few other details with tests, etc. but not that important.

Nonetheless, what you propose is a good addition for the gem so I've re-implemented it moving the logic to `ControllerAdditions` instead of `Keeper`. Also added much more tests, deprecation warnings where needed and improved the gems documentation to wrap it up.

The new version is **0.1.0**,  give it a try and let me know how it goes.

**Comment by god-anubis** [comment]
Took me some time to get my branch to resemble yours again (my git skills probably are not up to par). However your version works just as well, so obviously that's fine by me. I guess this pull request can be closed, but I seem unable to find a button or link that lets me do that.

**Comment by god-anubis** [comment]
Well just disproved myself of not finding the button.

**Comment by matiasgagliano** [comment]
Great, good to know it worked out and thanks for your support!

**Pull request closed without merging**
